services:
  db:
    image: postgres:16
    restart: unless-stopped
    env_file:
      - /opt/fuel-control/.env
      - _backup_env_2026-01-17_054429.env.production
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - fuelnet

  backend:
    build:
      context: ./src/backend
    env_file:
      - /opt/fuel-control/.env
      - _backup_env_2026-01-17_054429.env.production
    environment:
      BACKEND_PORT: 3000
    depends_on:
      - db
    ports:
      - "3000:3000" # изменить при желании внешний порт
    volumes:
      - ./data:/app/data
    networks:
      - fuelnet

  web:
    build:
      context: ./src/web
    env_file:
      - /opt/fuel-control/.env
      - _backup_env_2026-01-17_054429.env.production
    environment:
      API_BASE_URL: http://backend:3000
      PORT: 3001
    depends_on:
      - backend
    ports:
      - "3001:3001" # изменить при желании внешний порт
    networks:
      - fuelnet

volumes:
  db_data:

networks:
  fuelnet:
    driver: bridge
